PORTNAME=            libstubborn
DISTVERSION=         0.1
CATEGORIES=          games

USE_GITHUB=          yes
GH_ACCOUNT=          rfht
GH_PROJECT=          libstubborn

# MAKE_ARGS=           "PREFIX=${STAGEDIR}/${PREFIX}"

.include <bsd.port.mk>
