PORTNAME=            steamworks-nosteam
DISTVERSIONPREFIX=   v
DISTVERSION=         0.4.1
CATEGORIES=          games

USE_GITHUB=          yes
GH_ACCOUNT=          rfht
GH_PROJECT=          Steamworks-nosteam

LIB_DEPENDS=         libhl.so:lang/hashlink

USES=                mono
SSP_CFLAGS=
MAKE_ARGS=           "PREFIX=${STAGEDIR}/${PREFIX}"

.include <bsd.port.mk>
